// Vestavěná data pro drily. Bez volání AI – okamžité, offline, zdarma.
// Nepravidelná slovesa: [base, past simple, past participle, český význam, doplněk věty, úroveň]
export const IRREGULAR = [
  ["be", "was/were", "been", "být", "at home", "A1"],
  ["become", "became", "become", "stát se", "a teacher", "A2"],
  ["begin", "began", "begun", "začít", "the lesson", "A2"],
  ["break", "broke", "broken", "rozbít, zlomit", "the window", "A2"],
  ["bring", "brought", "brought", "přinést", "a present", "A2"],
  ["build", "built", "built", "postavit", "a house", "A2"],
  ["buy", "bought", "bought", "koupit", "a new phone", "A1"],
  ["catch", "caught", "caught", "chytit", "the bus", "A2"],
  ["choose", "chose", "chosen", "vybrat", "the red one", "A2"],
  ["come", "came", "come", "přijít", "to the party", "A1"],
  ["cost", "cost", "cost", "stát (cena)", "a lot of money", "A2"],
  ["cut", "cut", "cut", "řezat, stříhat", "the bread", "A2"],
  ["do", "did", "done", "dělat", "the homework", "A1"],
  ["draw", "drew", "drawn", "kreslit", "a picture", "A2"],
  ["drink", "drank", "drunk", "pít", "some water", "A1"],
  ["drive", "drove", "driven", "řídit", "to work", "A1"],
  ["eat", "ate", "eaten", "jíst", "breakfast", "A1"],
  ["fall", "fell", "fallen", "spadnout", "off the bike", "A2"],
  ["feel", "felt", "felt", "cítit (se)", "tired", "A2"],
  ["find", "found", "found", "najít", "the keys", "A1"],
  ["fly", "flew", "flown", "letět", "to Malta", "A2"],
  ["forget", "forgot", "forgotten", "zapomenout", "the name", "A2"],
  ["get", "got", "got", "dostat", "an email", "A1"],
  ["give", "gave", "given", "dát", "him a book", "A1"],
  ["go", "went", "gone", "jít, jet", "to the beach", "A1"],
  ["grow", "grew", "grown", "růst, pěstovat", "tomatoes", "A2"],
  ["have", "had", "had", "mít", "a good time", "A1"],
  ["hear", "heard", "heard", "slyšet", "the news", "A1"],
  ["hide", "hid", "hidden", "schovat", "the money", "B1"],
  ["hit", "hit", "hit", "udeřit, trefit", "the ball", "A2"],
  ["hold", "held", "held", "držet", "the door", "A2"],
  ["hurt", "hurt", "hurt", "zranit, bolet", "my leg", "A2"],
  ["keep", "kept", "kept", "nechat si, držet", "the receipt", "A2"],
  ["know", "knew", "known", "vědět, znát", "the answer", "A1"],
  ["learn", "learnt", "learnt", "učit se", "English", "A1"],
  ["leave", "left", "left", "odejít, nechat", "the office", "A1"],
  ["lend", "lent", "lent", "půjčit (někomu)", "her some money", "B1"],
  ["let", "let", "let", "nechat, dovolit", "the dog out", "A2"],
  ["lose", "lost", "lost", "ztratit", "my wallet", "A2"],
  ["make", "made", "made", "dělat, vyrobit", "a cake", "A1"],
  ["mean", "meant", "meant", "znamenat, myslet", "it", "A2"],
  ["meet", "met", "met", "potkat, sejít se", "a friend", "A1"],
  ["pay", "paid", "paid", "platit", "the bill", "A1"],
  ["put", "put", "put", "dát, položit", "it on the table", "A1"],
  ["read", "read", "read", "číst", "the newspaper", "A1"],
  ["ride", "rode", "ridden", "jet (na kole, koni)", "a bike", "A2"],
  ["ring", "rang", "rung", "zvonit, volat", "the bell", "A2"],
  ["run", "ran", "run", "běžet", "five kilometres", "A1"],
  ["say", "said", "said", "říct", "hello", "A1"],
  ["see", "saw", "seen", "vidět", "a film", "A1"],
  ["sell", "sold", "sold", "prodat", "the car", "A2"],
  ["send", "sent", "sent", "poslat", "a message", "A1"],
  ["show", "showed", "shown", "ukázat", "me the way", "A2"],
  ["shut", "shut", "shut", "zavřít", "the door", "A2"],
  ["sing", "sang", "sung", "zpívat", "a song", "A1"],
  ["sit", "sat", "sat", "sedět", "by the window", "A1"],
  ["sleep", "slept", "slept", "spát", "for eight hours", "A1"],
  ["speak", "spoke", "spoken", "mluvit", "to the manager", "A1"],
  ["spend", "spent", "spent", "utratit, strávit", "the weekend in Prague", "A2"],
  ["stand", "stood", "stood", "stát", "in the queue", "A2"],
  ["steal", "stole", "stolen", "ukrást", "the bike", "B1"],
  ["swim", "swam", "swum", "plavat", "in the sea", "A1"],
  ["take", "took", "taken", "vzít", "a photo", "A1"],
  ["teach", "taught", "taught", "učit (někoho)", "maths", "A2"],
  ["tell", "told", "told", "říct (někomu)", "her the truth", "A1"],
  ["think", "thought", "thought", "myslet", "about it", "A1"],
  ["throw", "threw", "thrown", "hodit", "the ball", "A2"],
  ["understand", "understood", "understood", "rozumět", "the question", "A1"],
  ["wake", "woke", "woken", "probudit (se)", "at six", "A2"],
  ["wear", "wore", "worn", "nosit (oblečení)", "a suit", "A2"],
  ["win", "won", "won", "vyhrát", "the match", "A2"],
  ["write", "wrote", "written", "psát", "an email", "A1"],
  ["bite", "bit", "bitten", "kousnout", "the apple", "B1"],
  ["blow", "blew", "blown", "foukat", "the candles out", "B1"],
  ["burn", "burnt", "burnt", "hořet, spálit", "the toast", "B1"],
  ["deal", "dealt", "dealt", "jednat, vypořádat se", "with the problem", "B1"],
  ["dream", "dreamt", "dreamt", "snít", "about the sea", "B1"],
  ["fight", "fought", "fought", "bojovat", "for the title", "B1"],
  ["forgive", "forgave", "forgiven", "odpustit", "him", "B1"],
  ["freeze", "froze", "frozen", "mrznout, zmrazit", "the meat", "B1"],
  ["hang", "hung", "hung", "pověsit", "the picture", "B1"],
  ["lead", "led", "led", "vést", "the team", "B1"],
  ["lie", "lay", "lain", "ležet", "on the sofa", "B1"],
  ["rise", "rose", "risen", "stoupat, vycházet", "at six", "B1"],
  ["set", "set", "set", "nastavit, položit", "the alarm", "B1"],
  ["shake", "shook", "shaken", "třást", "hands", "B1"],
  ["shine", "shone", "shone", "svítit", "all day", "B1"],
  ["shoot", "shot", "shot", "střílet", "the ball", "B1"],
  ["spread", "spread", "spread", "rozšířit, namazat", "the butter", "B1"],
  ["strike", "struck", "struck", "udeřit, stávkovat", "the wall", "B2"],
  ["tear", "tore", "torn", "roztrhnout", "the paper", "B1"],
];

// Frázová slovesa: [sloveso, částice, český význam, věta s ___ místo částice, oddělitelné?, úroveň, doplňková věta česky]
export const PHRASAL = [
  ["get", "up", "vstát", "I get ___ at seven every day.", false, "A1", "Vstávám v sedm."],
  ["wake", "up", "probudit se", "I wake ___ before the alarm.", true, "A1", "Probudím se před budíkem."],
  ["turn", "on", "zapnout", "Can you turn ___ the light?", true, "A1", "Můžeš zapnout světlo?"],
  ["turn", "off", "vypnout", "Turn ___ your phone in class.", true, "A1", "Ve třídě vypni telefon."],
  ["put", "on", "obléknout si", "Put ___ your jacket, it's cold.", true, "A1", "Vezmi si bundu, je zima."],
  ["take", "off", "sundat si", "Take ___ your shoes, please.", true, "A1", "Sundej si prosím boty."],
  ["look", "for", "hledat", "I'm looking ___ my keys.", false, "A1", "Hledám své klíče."],
  ["look", "after", "starat se o", "She looks ___ her little brother.", false, "A2", "Stará se o mladšího bratra."],
  ["look", "up", "vyhledat (v slovníku)", "Look ___ the word in the dictionary.", true, "A2", "Vyhledej to slovo ve slovníku."],
  ["look", "forward to", "těšit se na", "I'm looking ___ the weekend.", false, "A2", "Těším se na víkend."],
  ["give", "up", "vzdát se, přestat", "Don't give ___, keep trying!", true, "A2", "Nevzdávej to, zkoušej dál!"],
  ["give", "back", "vrátit", "Give ___ my pen, please.", true, "A2", "Vrať mi prosím pero."],
  ["pick", "up", "vyzvednout, zvednout", "I'll pick you ___ at the airport.", true, "A2", "Vyzvednu tě na letišti."],
  ["find", "out", "zjistit", "I want to find ___ the truth.", true, "A2", "Chci zjistit pravdu."],
  ["fill", "in", "vyplnit", "Please fill ___ this form.", true, "A2", "Prosím vyplňte tento formulář."],
  ["go", "on", "pokračovat", "Go ___, I'm listening.", false, "A2", "Pokračuj, poslouchám."],
  ["go", "out", "jít ven, chodit s někým", "We go ___ every Friday.", false, "A1", "Každý pátek chodíme ven."],
  ["come", "back", "vrátit se", "When will you come ___?", false, "A1", "Kdy se vrátíš?"],
  ["come", "in", "vejít", "Come ___ and sit down.", false, "A1", "Pojď dál a posaď se."],
  ["sit", "down", "sednout si", "Please sit ___.", false, "A1", "Prosím posaďte se."],
  ["stand", "up", "postavit se", "Stand ___ when the teacher comes in.", false, "A1", "Postav se, když přijde učitel."],
  ["grow", "up", "vyrůst", "I grew ___ in Prague.", false, "A2", "Vyrostl jsem v Praze."],
  ["hurry", "up", "pospíšit si", "Hurry ___, we're late!", false, "A1", "Pospěš si, máme zpoždění!"],
  ["check", "in", "zaregistrovat se (hotel, letiště)", "We checked ___ at the hotel at noon.", false, "A2", "V hotelu jsme se ubytovali v poledne."],
  ["check", "out", "odhlásit se (z hotelu)", "You have to check ___ before 11.", false, "A2", "Musíte se odhlásit před jedenáctou."],
  ["set", "off", "vyrazit (na cestu)", "We set ___ early in the morning.", false, "B1", "Vyrazili jsme brzy ráno."],
  ["carry", "on", "pokračovat", "Carry ___ with your work.", false, "B1", "Pokračuj v práci."],
  ["call", "back", "zavolat zpět", "I'll call you ___ later.", true, "A2", "Zavolám ti později zpátky."],
  ["hang", "up", "zavěsit (telefon)", "Don't hang ___, please!", false, "A2", "Nezavěšuj, prosím!"],
  ["switch", "on", "zapnout", "Switch ___ the computer.", true, "A2", "Zapni počítač."],
  ["throw", "away", "vyhodit", "Throw ___ the old newspapers.", true, "A2", "Vyhoď staré noviny."],
  ["run", "out of", "dojít (zásoba)", "We've run ___ milk.", false, "B1", "Došlo nám mléko."],
  ["get", "on", "nastoupit (bus, vlak)", "Get ___ the bus at the station.", false, "A2", "Nastup do autobusu na nádraží."],
  ["get", "off", "vystoupit", "Get ___ at the next stop.", false, "A2", "Vystup na příští zastávce."],
  ["get", "in", "nastoupit (auto)", "Get ___ the car, let's go.", false, "A2", "Nastup do auta, jedeme."],
  ["get", "back", "vrátit se", "We got ___ home at ten.", false, "A2", "Vrátili jsme se domů v deset."],
  ["get", "along with", "vycházet s", "I get ___ my colleagues.", false, "B1", "S kolegy vycházím dobře."],
  ["put", "off", "odložit", "Don't put ___ the meeting again.", true, "B1", "Neodkládej schůzku znovu."],
  ["put", "away", "uklidit", "Put ___ your books.", true, "A2", "Ukliď si knihy."],
  ["take", "up", "začít se věnovat (koníčku)", "I took ___ swimming last year.", true, "B1", "Minulý rok jsem začal plavat."],
  ["bring", "up", "vychovat; nadnést", "She brought ___ three children.", true, "B1", "Vychovala tři děti."],
  ["break", "down", "porouchat se", "My car broke ___ on the motorway.", false, "A2", "Auto se mi porouchalo na dálnici."],
  ["turn", "up", "objevit se; zesílit", "He turned ___ late again.", false, "B1", "Zase přišel pozdě."],
  ["turn", "down", "odmítnout; ztlumit", "They turned ___ my offer.", true, "B1", "Odmítli mou nabídku."],
  ["work", "out", "cvičit; vyřešit", "I work ___ three times a week.", false, "A2", "Cvičím třikrát týdně."],
  ["write", "down", "zapsat si", "Write ___ the address.", true, "A2", "Zapiš si adresu."],
  ["log", "in", "přihlásit se", "Log ___ with your password.", false, "A2", "Přihlas se svým heslem."],
  ["sign", "up", "zaregistrovat se", "I signed ___ for the course.", false, "A2", "Zapsal jsem se do kurzu."],
  ["show", "up", "ukázat se, dorazit", "He didn't show ___ at the meeting.", false, "B1", "Na schůzku nedorazil."],
  ["deal", "with", "vypořádat se s", "I'll deal ___ the problem tomorrow.", false, "B1", "S tím problémem se vypořádám zítra."],
  ["take", "care of", "postarat se o", "Who takes ___ the garden?", false, "A2", "Kdo se stará o zahradu?"],
  ["try", "on", "vyzkoušet si (oblečení)", "Can I try ___ these shoes?", true, "A2", "Můžu si vyzkoušet tyhle boty?"],
  ["pay", "back", "splatit", "I'll pay you ___ next week.", true, "B1", "Splatím ti to příští týden."],
  ["run", "into", "narazit na (potkat)", "I ran ___ Peter at the market.", false, "B1", "Na trhu jsem narazil na Petra."],
  ["make", "up", "vymyslet si; usmířit se", "He made ___ a story.", true, "B1", "Vymyslel si příběh."],
  ["cut", "down on", "omezit", "I should cut ___ sugar.", false, "B1", "Měl bych omezit cukr."],
  ["keep", "on", "pokračovat (dělat dál)", "Keep ___ practising every day.", false, "B1", "Cvič dál každý den."],
  ["move", "in", "nastěhovat se", "We moved ___ last month.", false, "A2", "Nastěhovali jsme se minulý měsíc."],
  ["move", "out", "odstěhovat se", "He moved ___ of his flat.", false, "A2", "Odstěhoval se ze svého bytu."],
  ["settle", "down", "usadit se", "They want to settle ___ in Spain.", false, "B1", "Chtějí se usadit ve Španělsku."],
];

export const PARTICLES = ["up", "down", "on", "off", "in", "out", "back", "away", "for", "after", "with", "into", "over", "through", "forward", "along", "care"];
