// Hovorové věty a otázky pro běžnou konverzaci: [anglicky, česky, kategorie, typ (q = otázka, s = věta), ukázková odpověď, úroveň]
export const PHRASES = [
  // Seznámení a pozdravy
  ["How's it going?", "Jak to jde?", "seznámení", "q", "Not bad, thanks. And you?", "A1"],
  ["Nice to meet you.", "Rád vás poznávám.", "seznámení", "s", "Nice to meet you too.", "A1"],
  ["Where are you from?", "Odkud jste?", "seznámení", "q", "I'm from the Czech Republic.", "A1"],
  ["What do you do?", "Co děláte (za práci)?", "seznámení", "q", "I work in real estate.", "A1"],
  ["How long have you been here?", "Jak dlouho tu jste?", "seznámení", "q", "About two weeks.", "A2"],
  ["Have a nice day!", "Hezký den!", "seznámení", "s", "You too!", "A1"],
  ["See you tomorrow.", "Uvidíme se zítra.", "seznámení", "s", "See you!", "A1"],
  ["Sorry, I didn't catch your name.", "Promiňte, nezachytil jsem vaše jméno.", "seznámení", "s", "It's Jan.", "A2"],
  ["Do you live here?", "Bydlíte tady?", "seznámení", "q", "No, I'm just visiting.", "A1"],
  ["What brings you to Malta?", "Co vás přivádí na Maltu?", "seznámení", "q", "I'm here to learn English.", "A2"],
  // Small talk
  ["What did you do at the weekend?", "Co jsi dělal o víkendu?", "small talk", "q", "I went to the beach.", "A2"],
  ["How was your day?", "Jaký jsi měl den?", "small talk", "q", "Pretty good, thanks.", "A1"],
  ["What's the weather like today?", "Jaké je dnes počasí?", "small talk", "q", "It's hot and sunny.", "A1"],
  ["Are you doing anything tonight?", "Děláš dnes večer něco?", "small talk", "q", "Not really, why?", "A2"],
  ["Do you have any plans for the weekend?", "Máš na víkend nějaké plány?", "small talk", "q", "I'm going sailing.", "A2"],
  ["I'm a bit tired today.", "Jsem dnes trochu unavený.", "small talk", "s", "Me too. It was a long day.", "A1"],
  ["Time flies!", "Ten čas letí!", "small talk", "s", "It really does.", "A2"],
  ["What do you think?", "Co si myslíš?", "small talk", "q", "I think it's a good idea.", "A1"],
  ["How do you like Malta so far?", "Jak se ti zatím líbí Malta?", "small talk", "q", "I love it. The sea is beautiful.", "A2"],
  ["That sounds great.", "To zní skvěle.", "small talk", "s", "Yeah, I think so too.", "A1"],
  // Nerozumím / zopakovat
  ["Sorry, could you say that again?", "Promiňte, můžete to říct znovu?", "porozumění", "q", "Sure. I said…", "A1"],
  ["Could you speak more slowly, please?", "Můžete mluvit pomaleji, prosím?", "porozumění", "q", "Of course, sorry.", "A1"],
  ["What does that mean?", "Co to znamená?", "porozumění", "q", "It means…", "A1"],
  ["How do you say that in English?", "Jak se to řekne anglicky?", "porozumění", "q", "You say…", "A1"],
  ["I'm not sure I understand.", "Nejsem si jistý, že rozumím.", "porozumění", "s", "Let me explain again.", "A2"],
  ["Could you spell that, please?", "Můžete to hláskovat, prosím?", "porozumění", "q", "Sure, J-A-N.", "A2"],
  ["Sorry, what was that?", "Promiň, co jsi říkal?", "porozumění", "q", "I asked if you're ready.", "A1"],
  ["Let me check.", "Podívám se.", "porozumění", "s", "OK, take your time.", "A2"],
  // Restaurace a kavárna
  ["Could I see the menu, please?", "Mohl bych dostat jídelní lístek?", "restaurace", "q", "Of course, here you are.", "A1"],
  ["I'd like a coffee, please.", "Dal bych si kávu, prosím.", "restaurace", "s", "Milk and sugar?", "A1"],
  ["Can we have the bill, please?", "Můžeme dostat účet, prosím?", "restaurace", "q", "Sure, one moment.", "A1"],
  ["What do you recommend?", "Co doporučujete?", "restaurace", "q", "The fish is very good today.", "A2"],
  ["Is this seat taken?", "Je tu obsazeno?", "restaurace", "q", "No, go ahead.", "A2"],
  ["Do you have a table for two?", "Máte stůl pro dva?", "restaurace", "q", "Yes, this way please.", "A1"],
  ["Can I pay by card?", "Můžu platit kartou?", "restaurace", "q", "Yes, of course.", "A1"],
  ["Everything was delicious, thank you.", "Všechno bylo výborné, děkuji.", "restaurace", "s", "I'm glad you enjoyed it.", "A2"],
  ["Could I have some water, please?", "Mohl bych dostat vodu, prosím?", "restaurace", "q", "Still or sparkling?", "A1"],
  ["I'm allergic to nuts.", "Mám alergii na ořechy.", "restaurace", "s", "OK, this dish has no nuts.", "A2"],
  // Nákupy
  ["How much is this?", "Kolik to stojí?", "nákupy", "q", "It's twenty euros.", "A1"],
  ["Do you have this in a bigger size?", "Máte to ve větší velikosti?", "nákupy", "q", "Let me check.", "A2"],
  ["I'm just looking, thanks.", "Jen se dívám, děkuji.", "nákupy", "s", "OK, let me know if you need help.", "A1"],
  ["Can I try it on?", "Můžu si to vyzkoušet?", "nákupy", "q", "Sure, the changing rooms are over there.", "A2"],
  ["I'll take it.", "Vezmu si to.", "nákupy", "s", "Great, anything else?", "A1"],
  ["Where can I find the milk?", "Kde najdu mléko?", "nákupy", "q", "It's in aisle three.", "A1"],
  ["Do you have a bag, please?", "Máte tašku, prosím?", "nákupy", "q", "Yes, that's ten cents.", "A1"],
  ["Is there a discount?", "Je na to sleva?", "nákupy", "q", "Yes, ten percent today.", "A2"],
  // Cesta a doprava
  ["Excuse me, where is the bus stop?", "Promiňte, kde je zastávka autobusu?", "cesta", "q", "It's just around the corner.", "A1"],
  ["How do I get to Valletta?", "Jak se dostanu do Valletty?", "cesta", "q", "Take bus number 13.", "A1"],
  ["Is it far from here?", "Je to odsud daleko?", "cesta", "q", "No, about ten minutes on foot.", "A1"],
  ["Which bus goes to the airport?", "Který autobus jede na letiště?", "cesta", "q", "The X4 goes there.", "A2"],
  ["Does this bus stop at the beach?", "Staví tenhle autobus u pláže?", "cesta", "q", "Yes, get off at the third stop.", "A2"],
  ["Could you tell me when to get off?", "Můžete mi říct, kdy vystoupit?", "cesta", "q", "Sure, I'll let you know.", "A2"],
  ["A return ticket to Sliema, please.", "Zpáteční lístek do Sliemy, prosím.", "cesta", "s", "That's three euros.", "A1"],
  ["What time is the last bus?", "V kolik jede poslední autobus?", "cesta", "q", "At half past eleven.", "A2"],
  ["I think we're lost.", "Myslím, že jsme se ztratili.", "cesta", "s", "Let's look at the map.", "A2"],
  ["Turn left at the traffic lights.", "Na semaforu zahněte doleva.", "cesta", "s", "OK, thank you.", "A1"],
  // Škola a učení
  ["Can you help me with this exercise?", "Můžeš mi pomoct s tímhle cvičením?", "škola", "q", "Sure, which one?", "A1"],
  ["What page are we on?", "Na které jsme stránce?", "škola", "q", "Page forty-two.", "A1"],
  ["I didn't do my homework.", "Neudělal jsem domácí úkol.", "škola", "s", "Try to do it for tomorrow.", "A1"],
  ["Could you explain that again?", "Můžete to vysvětlit znovu?", "škola", "q", "Of course.", "A2"],
  ["What's the difference between these two words?", "Jaký je rozdíl mezi těmito dvěma slovy?", "škola", "q", "One is formal, the other isn't.", "A2"],
  ["Is this correct?", "Je to správně?", "škola", "q", "Almost. Check the verb.", "A1"],
  ["How do you pronounce this word?", "Jak se vyslovuje tohle slovo?", "škola", "q", "Listen: …", "A2"],
  ["I have a question.", "Mám otázku.", "škola", "s", "Go ahead.", "A1"],
  // Telefon a domluva
  ["Can I call you back later?", "Můžu ti zavolat později?", "telefon", "q", "Sure, no problem.", "A2"],
  ["Sorry, I'm busy right now.", "Promiň, teď mám práci.", "telefon", "s", "OK, talk later.", "A1"],
  ["What time shall we meet?", "V kolik se sejdeme?", "domluva", "q", "How about seven?", "A2"],
  ["Where shall we meet?", "Kde se sejdeme?", "domluva", "q", "In front of the school.", "A2"],
  ["Does Friday work for you?", "Vyhovuje ti pátek?", "domluva", "q", "Friday is fine.", "A2"],
  ["I'm running late, sorry.", "Mám zpoždění, promiň.", "domluva", "s", "No problem, take your time.", "A2"],
  ["Let's meet at six.", "Sejdeme se v šest.", "domluva", "s", "Perfect, see you then.", "A1"],
  ["Can we change the time?", "Můžeme změnit čas?", "domluva", "q", "Sure, what time suits you?", "A2"],
  ["I'll text you.", "Napíšu ti.", "domluva", "s", "OK, thanks.", "A1"],
  ["Are you free tomorrow?", "Máš zítra čas?", "domluva", "q", "Yes, in the afternoon.", "A1"],
  // Souhlas, nesouhlas, názor
  ["I agree with you.", "Souhlasím s tebou.", "názor", "s", "Great, so we're on the same page.", "A2"],
  ["I'm not sure about that.", "Tím si nejsem jistý.", "názor", "s", "Why not?", "A2"],
  ["That's a good point.", "To je dobrá poznámka.", "názor", "s", "Thanks.", "A2"],
  ["I don't think so.", "Myslím, že ne.", "názor", "s", "Really? Why?", "A1"],
  ["It depends.", "Přijde na to.", "názor", "s", "On what?", "A2"],
  ["In my opinion, it's too expensive.", "Podle mě je to moc drahé.", "názor", "s", "Maybe you're right.", "A2"],
  ["What would you do?", "Co bys dělal ty?", "názor", "q", "I'd wait a bit.", "A2"],
  ["Are you serious?", "Myslíš to vážně?", "názor", "q", "Yes, totally.", "A2"],
  // Pomoc a zdvořilost
  ["Could you do me a favour?", "Mohl bys mi udělat laskavost?", "zdvořilost", "q", "Sure, what do you need?", "A2"],
  ["Thanks a lot, I appreciate it.", "Moc děkuji, vážím si toho.", "zdvořilost", "s", "You're welcome.", "A2"],
  ["No worries.", "V pohodě.", "zdvořilost", "s", "Thanks.", "A2"],
  ["Excuse me, is anyone sitting here?", "Promiňte, sedí tu někdo?", "zdvořilost", "q", "No, it's free.", "A2"],
  ["Sorry to bother you.", "Promiňte, že obtěžuji.", "zdvořilost", "s", "No problem, how can I help?", "A2"],
  ["After you.", "Až po vás.", "zdvořilost", "s", "Thank you.", "A1"],
  ["Would you mind opening the window?", "Nevadilo by vám otevřít okno?", "zdvořilost", "q", "Not at all.", "A2"],
  ["Can I help you with that?", "Můžu vám s tím pomoct?", "zdvořilost", "q", "That's very kind, thanks.", "A1"],
  // Pocity a zdraví
  ["I don't feel very well.", "Není mi moc dobře.", "zdraví", "s", "Oh no, what's wrong?", "A1"],
  ["I've got a headache.", "Bolí mě hlava.", "zdraví", "s", "You should take a painkiller.", "A2"],
  ["Get well soon!", "Brzy se uzdrav!", "zdraví", "s", "Thanks.", "A1"],
  ["Are you OK?", "Jsi v pořádku?", "zdraví", "q", "Yes, I'm fine, just tired.", "A1"],
  ["I need to see a doctor.", "Potřebuji k doktorovi.", "zdraví", "s", "There's a clinic near the school.", "A2"],
  ["I'm so happy for you!", "Mám z tebe takovou radost!", "pocity", "s", "Thank you!", "A2"],
  ["I'm a bit nervous.", "Jsem trochu nervózní.", "pocity", "s", "Don't worry, you'll be fine.", "A2"],
  ["What's wrong?", "Co se děje?", "pocity", "q", "Nothing, I'm just tired.", "A1"],
  // Práce a byznys
  ["What do you do for a living?", "Čím se živíte?", "práce", "q", "I run a small company.", "A2"],
  ["I work for myself.", "Podnikám sám na sebe.", "práce", "s", "That must be interesting.", "A2"],
  ["We rent flats to tourists.", "Pronajímáme byty turistům.", "práce", "s", "Where are the flats?", "A2"],
  ["I have a meeting at ten.", "V deset mám schůzku.", "práce", "s", "OK, let's talk after.", "A1"],
  ["Could you send me the details?", "Můžete mi poslat podrobnosti?", "práce", "q", "Sure, I'll email you.", "A2"],
  ["Let me think about it.", "Nech mě si to rozmyslet.", "práce", "s", "Of course, take your time.", "A2"],
  ["What's your budget?", "Jaký máte rozpočet?", "práce", "q", "Around two thousand euros.", "A2"],
  ["That works for me.", "To mi vyhovuje.", "práce", "s", "Great, it's a deal.", "A2"],
  // Hotel a ubytování
  ["I have a reservation.", "Mám rezervaci.", "hotel", "s", "What's your name, please?", "A1"],
  ["What time is breakfast?", "V kolik je snídaně?", "hotel", "q", "From seven to ten.", "A1"],
  ["The air conditioning doesn't work.", "Klimatizace nefunguje.", "hotel", "s", "I'll send someone right away.", "A2"],
  ["Could I have a late check-out?", "Mohl bych mít pozdější odhlášení?", "hotel", "q", "Yes, until one o'clock.", "A2"],
  ["Is there Wi-Fi in the room?", "Je na pokoji wifi?", "hotel", "q", "Yes, the password is on the card.", "A1"],
  ["Could you call me a taxi?", "Můžete mi zavolat taxi?", "hotel", "q", "Of course, for what time?", "A2"],
  // Loď a moře (Malta)
  ["Is the sea calm today?", "Je dnes moře klidné?", "moře", "q", "Yes, it's perfect for sailing.", "A2"],
  ["What time do we leave?", "V kolik vyplouváme?", "moře", "q", "At nine, if the wind is OK.", "A1"],
  ["Where can I rent a boat?", "Kde si můžu půjčit loď?", "moře", "q", "There's a marina in Kalkara.", "A2"],
  ["Is it safe to swim here?", "Je bezpečné tu plavat?", "moře", "q", "Yes, but watch out for jellyfish.", "A2"],
  ["How much is the fuel?", "Kolik stojí palivo?", "moře", "q", "About one euro fifty a litre.", "A2"],
];
